POST http://localhost:8080/callback-logger/api/callback
Content-Type: application/json

{
  "clientId": "test_client_id",
  "requestId": "VCpcFPowVwzX",
  "timestamp": "2023-04-14T09:18:22.132Z",
  "finished": false
}


###
# curl -X POST --location "http://localhost:8080/callback-logger/api/callback" 
#    -H "Content-Type: application/json" 
#    -d '{
#          "clientId": "test_client_id",
#          "requestId": "VCpcFPowVwzX",
#          "timestamp": "2023-04-14T09:18:22.132Z",
#          "finished": false
#        }'

###


PUT http://localhost:8080/callback-logger/api/callback
Content-Type: application/xml

<CATALOG>
    <PLANT>
        <COMMON>Bloodroot</COMMON>
        <BOTANICAL>Sanguinaria canadensis</BOTANICAL>
        <ZONE>4</ZONE>
        <LIGHT>Mostly Shady</LIGHT>
        <PRICE>$2.44</PRICE>
        <AVAILABILITY>031599</AVAILABILITY>
    </PLANT>
</CATALOG>

###

# curl -X PUT --location "http://localhost:8080/callback-logger/api/callback" 
#    -H "Content-Type: application/xml" 
#    -d '<CATALOG>
#    <PLANT>
#        <COMMON>Bloodroot</COMMON>
#        <BOTANICAL>Sanguinaria canadensis</BOTANICAL>
#        <ZONE>4</ZONE>
#        <LIGHT>Mostly Shady</LIGHT>
#        <PRICE>$2.44</PRICE>
#        <AVAILABILITY>031599</AVAILABILITY>
#    </PLANT>
#</CATALOG>'

###
